name: typofixer-pt-br
parent: default
matches:
      - trigger: excessão
        replace: exceção
        propagate_case: true
        word: true
      
      - trigger: ancioso
        replace: ansioso
        propagate_case: true
        word: true
      
      - trigger: subcídio
        replace: subsídio
        propagate_case: true
        word: true
      
      - trigger: paralizado
        replace: paralisado
        propagate_case: true
        word: true
      
      - trigger: licensa
        replace: licença
        propagate_case: true
        word: true
      
      - trigger: descanço
        replace: descanso
        propagate_case: true
        word: true
      
      - trigger: cançaço
        replace: cansaço
        propagate_case: true
        word: true
      
      - trigger: ascenção
        replace: ascensão
        propagate_case: true
        word: true
      
      - trigger: encomodar
        replace: incomodar
        propagate_case: true
        word: true
      
      - trigger: extender
        replace: estender
        propagate_case: true
        word: true
      
      - trigger: concerteza
        replace: com certeza
        propagate_case: true
        word: true
      
      - trigger: derrepente
        replace: de repente
        propagate_case: true
        word: true
      
      - trigger: porisso
        replace: por isso
        propagate_case: true
        word: true
      
      - trigger: apartir de
        replace: a partir de
        propagate_case: true
        word: true
      
      - trigger: mecher
        replace: mexer
        propagate_case: true
        word: true
      
      - trigger: chingar
        replace: xingar
        propagate_case: true
        word: true
      
      - trigger: xuxu
        replace: chuchu
        propagate_case: true
        word: true
      
      - trigger: geito
        replace: jeito
        propagate_case: true
        word: true
      
      - trigger: beje
        replace: bege
        propagate_case: true
        word: true
      
      - trigger: quiz
        replace: quis
        propagate_case: true
        word: true